repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: Formatting (black)
        entry: black
        types: [python]
        language: python
        args : ["--line-length", "100"]
      - id: isort
        name: Sorting imports (isort)
        entry: isort
        types: [python]
        language: python
        args: ["--profile", "black"]
      - id: nbstripout
        name: Strip Jupyter notebook output (nbstripout)
        entry: nbstripout
        types: [file]
        files: (.ipynb)$
        language: python
      - id: darglint
        name: Darglint
        entry: darglint
        types: [python]
        language: python

exclude: ^(.svn|CVS|.bzr|.hg|.git|__pycache__|.tox|.ipynb_checkpoints|assets|tests/assets/|venv/|.venv/)
